# Version: 0.0.1
FROM openjdk:8-jdk-alpine 
VOLUME /tmp 
COPY target/UserRoleApi-0.0.1-SNAPSHOT.jar ApiRole.jar 
ENV server.port=8081
ENV spring.datasource.url=jdbc:mysql://host.docker.internal:3306/BookLibraryDB?createDatabaseIfNotExist=true
ENV spring.datasource.username=root
ENV spring.datasource.password=
ENV spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
ENV spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL55Dialect
ENV spring.jpa.generate-ddl=true
ENV spring.jpa.hibernate.ddl-auto=update
ENV eureka.client.serviceUrl.defaultZone=http://ayoub:ayoub123456passEurek@host.docker.internal:8761/eureka
ENV spring.application.name=api-role
ENV spring.rabbitmq.host=host.docker.internal
LABEL version="1.0"
LABEL author="Ayoub oukach" role="Developer" email="oukachayoub@gmail.com"
#RUN apt-get -qq update
#EXPOSE 8081
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ApiRole.jar"] 
#CMD ["/bin/bash", "-l"]
#ADD, WORKDIR, USER, ONBUILD, STOPSIGNAL, ARG, SHELL, HEALTHCHECK
#ENV TARGET_DIR /opt/app
#WORKDIR $TARGET_DIR